//! Wallets whose entropy buffer was only partly filled.
//!
//! Every other vulnerability here is a weak *generator*. This one is a weak *call*: the
//! generator may have been perfect, but only some of the bytes it should have produced
//! ever reached the buffer, and the rest stayed as the allocator left them -- zero. A
//! 256-bit wallet with 32 bits of real entropy is as guessable as a 32-bit seed, and it
//! looks completely normal from the outside: the mnemonic has the right word count and a
//! valid checksum.
//!
//! This has happened repeatedly and in more than one shape: a read that returned fewer
//! bytes than asked for and went unchecked, a loop bound written against the wrong
//! length, an `int` truncated to a smaller type on the way in, and randomness that
//! silently failed and returned zeros.
//!
//! # Point zero is a real wallet
//!
//! All-zero entropy is the mnemonic `abandon abandon ... about`, which is the first
//! published BIP39 test vector and one of the most-funded accidental addresses in
//! Bitcoin -- people paste the test vector in and send coins to it. It is the first
//! point of this space, which is also what makes the whole plugin easy to check: point
//! zero has to produce a mnemonic anyone can look up.

use crate::scan::derive::Route;
use crate::vuln::{Defaults, Expanded, Guide, KernelSpec, Point, Space, Vulnerability};

/// The device half of [`TruncatedEntropy::expand`].
const KERNEL_SOURCE: &str = include_str!("../../kernels/vuln/truncated.h");

/// Bytes of real randomness assumed to have reached the buffer.
///
/// Four, because that is both the common case -- a 32-bit value written where a longer
/// one was meant -- and the largest prefix a full sweep can cover. A user who suspects a
/// different width can narrow `--end` to scan fewer.
const RANDOM_PREFIX: usize = 4;

/// BIP39 entropy whose first bytes are random and whose remainder is zero.
pub struct TruncatedEntropy;

impl Vulnerability for TruncatedEntropy {
    fn id(&self) -> &'static str {
        "truncated-entropy"
    }

    fn classification(&self) -> &'static str {
        "no CVE -- a call-site bug, not a generator"
    }
    fn aliases(&self) -> &'static [&'static str] {
        &["truncated", "short-entropy"]
    }

    fn describe(&self) -> Vec<String> {
        vec![
            format!(
                "BIP39 entropy with only the first {RANDOM_PREFIX} bytes random and the \
                 rest left zero, which is what an unchecked short read or a wrong loop \
                 bound produces. The generator may have been sound; the buffer was not. \
                 Point 0 is the all-zero `abandon ... about` wallet."
            ),
        ]
    }

    fn guide(&self) -> Guide {
        Guide {
            what: "Some wallets ask for 32 bytes of randomness and only get a few, \
                   leaving the rest of the buffer as zeros. The mnemonic still has the \
                   right number of words and a valid checksum, so nothing looks wrong -- \
                   but the wallet has about as much real randomness as a 32-bit number.",
            affected: "No single product: this is an unchecked short read or a wrong loop \
                       bound at the point randomness is collected, and it has happened in \
                       several wallets independently. Worth running against any wallet \
                       you suspect was generated by hand-rolled code.",
            command: "keyforge scan --vuln truncated-entropy -f funded.bf",
            time: "About 9 days on a laptop, or 9 hours on a recent NVIDIA card. If you \
                   suspect fewer random bytes than four, narrow --end: two bytes is \
                   --end 65536, which finishes instantly.",
            hit: "One mnemonic phrase per line in matches.txt. Note that the very first \
                  point is the well-known all-zero test-vector wallet, which receives \
                  stray funds constantly and is not evidence of this bug.",
        }
    }

    fn space(&self) -> Space {
        Space::Integers { start: 0, end: 1 << (8 * RANDOM_PREFIX as u32) }
    }

    /// The bug is in how BIP39 entropy was collected, so the BIP39 route is the one that
    /// matters. The raw-seed route is kept because the same short buffer would have been
    /// just as wrong fed straight to BIP32; the privkey route is not, since a key with 28
    /// zero bytes is covered far more cheaply by `low-int`.
    fn defaults(&self) -> Defaults {
        Defaults {
            material_sizes: vec![16, 24, 32],
            routes: vec![Route::Bip39, Route::Bip32Seed],
            paths: Vec::new(),
        }
    }

    fn expand_at(&self, point: Point<'_>, _offsets: &[usize], out: &mut Vec<Expanded>) {
        let Point::Integer(n) = point else {
            debug_assert!(false, "truncated-entropy does not read a corpus");
            return;
        };
        // Big-endian in the leading bytes: the buffer is filled front to back, so the
        // bytes that arrived are the ones at the start and the zeros are the tail.
        let mut material = [0u8; 32];
        let bytes = (n as u32).to_be_bytes();
        material[..RANDOM_PREFIX].copy_from_slice(&bytes[4 - RANDOM_PREFIX..]);
        out.push(material);
    }

    /// One stream, and the prefix width goes with it: a kernel that disagreed with the
    /// host about how many bytes are random would scan a different space entirely.
    /// No stream to offset into, so one walk at the front of it -- `offset_step` is
    /// `None`, which is what stops `--offset` reaching here at all.
    fn kernel_at(&self, _offsets: &[usize]) -> Option<KernelSpec> {
        Some(KernelSpec {
            source: KERNEL_SOURCE,
            streams: vec![0],
            offsets: vec![0],
            defines: vec![("VULN_RANDOM_PREFIX", format!("{RANDOM_PREFIX}u"))],
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::wallet::bip39;

    /// Point zero is all-zero entropy, whose mnemonics are the first published BIP39
    /// test vectors at every word count. Ground truth from the specification.
    #[test]
    fn point_zero_is_the_published_all_zero_vector() {
        let mut out = Vec::new();
        TruncatedEntropy.expand(Point::Integer(0), &mut out);
        assert_eq!(out[0], [0u8; 32]);

        assert_eq!(
            bip39::mnemonic(&out[0][..16]),
            "abandon abandon abandon abandon abandon abandon \
             abandon abandon abandon abandon abandon about"
        );
        assert_eq!(
            bip39::mnemonic(&out[0][..24]),
            "abandon abandon abandon abandon abandon abandon abandon abandon abandon \
             abandon abandon abandon abandon abandon abandon abandon abandon agent"
        );
        assert_eq!(
            bip39::mnemonic(&out[0][..32]),
            "abandon abandon abandon abandon abandon abandon abandon abandon abandon \
             abandon abandon abandon abandon abandon abandon abandon abandon abandon \
             abandon abandon abandon abandon abandon art"
        );
    }

    /// Only the first bytes vary; everything after them must stay zero, or this is not
    /// the bug being modelled.
    #[test]
    fn only_the_leading_bytes_are_random() {
        for n in [1u128, 255, 256, 65535, 0xdead_beef] {
            let mut out = Vec::new();
            TruncatedEntropy.expand(Point::Integer(n), &mut out);
            assert_eq!(
                &out[0][RANDOM_PREFIX..],
                &[0u8; 32 - RANDOM_PREFIX][..],
                "point {n} wrote outside the random prefix"
            );
            assert_eq!(
                u32::from_be_bytes(out[0][..4].try_into().unwrap()),
                n as u32,
                "point {n} did not land in the prefix big-endian"
            );
        }
    }

    /// The space must cover exactly the prefix it claims -- no more, since those points
    /// are unreachable, and no less, since those wallets would be missed.
    #[test]
    fn the_space_is_exactly_the_random_prefix() {
        assert_eq!(TruncatedEntropy.space().len(), Some(1 << (8 * RANDOM_PREFIX as u32)));
    }

    /// Distinct points must give distinct wallets.
    #[test]
    fn distinct_points_give_distinct_material() {
        let mut seen = std::collections::HashSet::new();
        for n in 0..64u128 {
            let mut out = Vec::new();
            TruncatedEntropy.expand(Point::Integer(n), &mut out);
            assert!(seen.insert(out[0]), "point {n} repeated an earlier wallet");
        }
    }
}
