//! Assembling the kernel translation unit.
//!
//! Neither runtime compiler resolves `#include` of a local file -- Metal's
//! `newLibraryWithSource` and NVRTC both take a single string -- so the headers under
//! `kernels/` are concatenated here, in dependency order, into one translation unit. That
//! is the whole of what a `build.rs` would have done, in a dozen lines, with the bonus
//! that the result is a `&str` a test can compile without a GPU present.
//!
//! The scope is prepended as `#define`s rather than passed as kernel arguments. It is
//! fixed for the life of a run, so baking it in unrolls every level loop and turns every
//! stride into a compile-time constant; a `--entropy 32 --indices 1` sweep gets a kernel
//! that knows it. The cost is a compile at startup, measured at a few hundred
//! milliseconds against a sweep measured in days.

use crate::gpu::Layout;
use crate::scan::derive::Route;
use crate::vuln::Vulnerability;
use crate::wallet::address::HashForm;

/// Which dialect the assembled source is for.
///
/// The kernels are written once against the macros in `compat.h`; this only decides which
/// of the two branches in that header is taken.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Dialect {
    Metal,
    Cuda,
}

impl Dialect {
    fn define(self) -> &'static str {
        match self {
            Dialect::Metal => "#define KEYFORGE_METAL 1\n",
            Dialect::Cuda => "#define KEYFORGE_CUDA 1\n",
        }
    }
}

/// The headers, in the order they must be concatenated.
///
/// Order is dependency order and is not incidental: `compat.h` defines the address-space
/// and index macros everything else is written against, `field.h` underpins `ec.h`, and
/// `kernels.h` uses all of them. Adding a header means adding it here.
const HEADERS: &[(&str, &str)] = &[
    ("compat.h", include_str!("../../kernels/compat.h")),
    ("field.h", include_str!("../../kernels/field.h")),
    ("scalar.h", include_str!("../../kernels/scalar.h")),
    ("sha256.h", include_str!("../../kernels/sha256.h")),
    ("ripemd160.h", include_str!("../../kernels/ripemd160.h")),
    ("sha512.h", include_str!("../../kernels/sha512.h")),
    ("mt19937.h", include_str!("../../kernels/mt19937.h")),
    ("bip39.h", include_str!("../../kernels/bip39.h")),
    ("bloom.h", include_str!("../../kernels/bloom.h")),
    ("ec.h", include_str!("../../kernels/ec.h")),
    ("kernels.h", include_str!("../../kernels/kernels.h")),
];

/// The dialect this build's backend speaks.
///
/// One place, because there are two callers -- the pipeline and the parity harness -- and
/// when they disagree the failure is baffling: the harness assembled Metal source on a
/// CUDA machine and NVRTC reported "could not open source file metal_stdlib", which reads
/// like a broken toolchain rather than a wrong constant.
pub fn dialect() -> Dialect {
    // Metal wins where both are compiled in, which can only be a Mac -- and a Mac has no
    // CUDA device to find anyway.
    if cfg!(feature = "metal") {
        Dialect::Metal
    } else {
        Dialect::Cuda
    }
}

/// Build the translation unit for `layout` in `dialect`.
pub fn assemble(layout: &Layout, v: &dyn Vulnerability, dialect: Dialect) -> String {
    let mut out = String::with_capacity(64 * 1024);
    out.push_str("// Generated by keyforge gpu::source::assemble. Do not edit.\n");
    out.push_str(dialect.define());
    out.push_str(&defines(layout));

    for (name, body) in HEADERS {
        // A line comment rather than `#line`: the runtime compilers report offsets into
        // the string they were handed, and a name in the text is what makes an error
        // message locatable in the original file.
        out.push_str(&format!("\n// ---------------- kernels/{name} ----------------\n"));
        out.push_str(body);
        // The vulnerability's own kernel goes in immediately before `kernels.h`, which is
        // the only file that calls `vuln_expand`. Everything ahead of it is shared, and
        // that split is what makes a new vulnerability a small piece of work.
        if *name == "ec.h" {
            out.push_str("\n// ---------------- the vulnerability ----------------\n");
            out.push_str(&vuln_defines(v));
        }
    }
    out
}

/// The scope, as preprocessor constants.
fn defines(l: &Layout) -> String {
    let mut d = String::new();
    let mut def = |k: &str, v: String| d.push_str(&format!("#define {k} {v}\n"));

    def("N_ENTROPY_SIZES", l.material_sizes.len().to_string());
    def("ENTROPY_SIZES", list(&l.material_sizes));
    def("N_HD_VARIANTS", l.tree_routes.len().to_string());
    def(
        "HD_VARIANTS",
        list(&l.tree_routes.iter().map(|r| route_code(*r)).collect::<Vec<_>>()),
    );
    def("N_RAW_SIZES", l.raw_sizes.len().to_string());
    def("RAW_SIZES", list(&l.raw_sizes));
    def("HAS_BIP39", u32::from(l.tree_routes.contains(&Route::Bip39)).to_string());
    def("N_FORMS", l.forms.len().to_string());
    def("FORMS", list(&l.forms.iter().map(|f| form_code(*f)).collect::<Vec<_>>()));

    // The leaf array's regions, so `k_leaf` can name the point a slot came from without a
    // mixed-radix decode. Per point, because the boundaries move with the launch size.
    def("N_REGIONS", l.regions.len().to_string());
    def(
        "REGION_BASES",
        list(&l.regions.iter().map(|r| format!("{}u", r.base_per_point)).collect::<Vec<_>>()),
    );
    def(
        "REGION_PER_POINT",
        list(&l.regions.iter().map(|r| format!("{}u", r.per_point)).collect::<Vec<_>>()),
    );

    // The comb's shape, from `ec` rather than restated, so the two can only be retuned
    // together. The kernel recodes digits itself and needs these as constants.
    let (window, rows, _row_len) = crate::crypto::ec::comb_shape();
    def("EC_WINDOW", window.to_string());
    def("EC_ROWS", rows.to_string());

    def("MASTERS_PER_SEED", l.masters_per_point().to_string());
    def("LEAVES_PER_SEED", l.leaves_per_point().to_string());
    def("HASHES_PER_SEED", l.hashes_per_point().to_string());
    d
}

/// The vulnerability's own constants and its `vuln_expand`.
///
/// Everything above this in the translation unit is shared; this is the only part that
/// knows which vulnerability is being swept. A plugin that returns no kernel is CPU-only
/// and never reaches here.
fn vuln_defines(v: &dyn Vulnerability) -> String {
    let spec = v.kernel().expect("a GPU build needs a kernel");
    let mut d = String::new();
    d.push_str(&format!("#define N_STREAMS {}\n", spec.streams.len()));
    d.push_str(&format!(
        "#define VULN_STREAMS {}\n",
        list(&spec.streams.iter().map(|s| format!("{s}u")).collect::<Vec<_>>())
    ));
    for (k, val) in spec.defines {
        d.push_str(&format!("#define {k} {val}\n"));
    }
    d.push_str(spec.source);
    d.push('\n');
    d
}

/// A C array initialiser body: `{ a, b, c }`.
///
/// Never empty. A zero-length array is illegal in C++ and both kernel compilers reject it,
/// so a scope that empties one of these -- `--variants raw-privkey` leaves no HD variants,
/// `--variants bip39` leaves no raw sizes -- would otherwise produce source that cannot
/// compile. The placeholder is never read: every loop over one of these arrays is bounded
/// by the matching `N_*` count, which is genuinely zero.
///
/// This was a live bug, and it hid because the test that covered it skipped on any error
/// opening a GPU. Failing to compile the kernels looked exactly like having no GPU.
fn list<T: std::fmt::Display>(items: &[T]) -> String {
    if items.is_empty() {
        return "{ 0 }".to_string();
    }
    let inner: Vec<String> = items.iter().map(|i| i.to_string()).collect();
    format!("{{ {} }}", inner.join(", "))
}

/// The kernel-side encoding of a `Route`. Mirrored by `VARIANT_*` in `compat.h`.
fn route_code(r: Route) -> u32 {
    match r {
        Route::Bip39 => 0,
        Route::Bip32Seed => 1,
        Route::PrivKey => 2,
    }
}

/// The kernel-side encoding of a `HashForm`. Mirrored by `FORM_*` in `compat.h`.
fn form_code(f: HashForm) -> u32 {
    match f {
        HashForm::Compressed => 0,
        HashForm::Uncompressed => 1,
        HashForm::P2shP2wpkh => 2,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::scan::derive::Scope;
    use crate::vuln::mt19937::MilkSad;

    fn source_for(scope: &Scope) -> String {
        assemble(&Layout::new(scope, 1), &MilkSad, Dialect::Metal)
    }

    /// The scope has to reach the kernels, and the region table with it -- that table is
    /// how a leaf slot names its point, and a wrong one makes every hit unconfirmable.
    #[test]
    fn the_scope_reaches_the_kernels_as_constants() {
        let src = source_for(&Scope::default());
        for want in [
            "#define N_ENTROPY_SIZES 3",
            "#define ENTROPY_SIZES { 16, 24, 32 }",
            "#define N_REGIONS 5",
            "#define HAS_BIP39 1",
            "#define N_FORMS 3",
        ] {
            assert!(src.contains(want), "missing `{want}`");
        }
        // 4 path specs plus the region for keys with no path.
        assert!(
            src.contains("#define REGION_PER_POINT { 120u, 120u, 120u, 120u, 1u }"),
            "the region table is wrong; a leaf slot would name the wrong point"
        );
    }

    /// The vulnerability's own kernel must land *before* `kernels.h`, which is the only
    /// file that calls `vuln_expand`. Ordering this wrong is a compile error on the device
    /// and nowhere else, so it is worth a test that needs no device.
    #[test]
    fn the_vulnerability_kernel_precedes_the_pipeline() {
        let src = source_for(&Scope::default());
        let expand = src.find("vuln_expand").expect("the plugin defines vuln_expand");
        let pipeline = src.find("KERNEL k_entropy").expect("the pipeline calls it");
        assert!(expand < pipeline, "the plugin kernel is assembled after its caller");
        assert!(src.contains("#define N_STREAMS 2"), "milksad walks two streams");
    }

    /// A scope that empties one of the constant arrays must still produce compilable
    /// source. A zero-length array is illegal in C++ and both kernel compilers reject it.
    ///
    /// This was a live bug once, and it hid because the test that covered it skipped on
    /// any error opening a GPU -- failing to compile the kernels looked exactly like
    /// having no GPU at all.
    #[test]
    fn an_emptied_array_still_yields_compilable_source() {
        use crate::scan::derive::Route;
        use crate::wallet::address::HashForm;

        let privkey_only = Scope {
            material_sizes: vec![32],
            routes: vec![Route::PrivKey],
            paths: vec![],
            forms: vec![HashForm::Compressed],
        };
        let src = source_for(&privkey_only);
        assert!(!src.contains("{ }"), "an empty array initialiser reached the source");
        assert!(src.contains("#define N_HD_VARIANTS 0"));
        assert!(src.contains("#define HAS_BIP39 0"));
        // One region: the keys with no path.
        assert!(src.contains("#define N_REGIONS 1"));
    }

    /// Both dialects must be produced from the same text, differing only in which branch
    /// of `compat.h` is taken.
    #[test]
    fn the_two_dialects_differ_only_in_their_marker() {
        let layout = Layout::new(&Scope::default(), 1);
        let metal = assemble(&layout, &MilkSad, Dialect::Metal);
        let cuda = assemble(&layout, &MilkSad, Dialect::Cuda);
        assert!(metal.contains("#define KEYFORGE_METAL 1"));
        assert!(cuda.contains("#define KEYFORGE_CUDA 1"));
        assert_eq!(metal.len() - "#define KEYFORGE_METAL 1\n".len(),
                   cuda.len() - "#define KEYFORGE_CUDA 1\n".len());
    }
}
